"""
PDF Report Generator for Impact Analysis
Oracle Pythia-26 Hackathon | Team AI Elites (LTM) — Sameet, Rahul, Suraj, Arpan

Generates a professional PDF impact analysis report using reportlab.
"""

import io
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate,
    Table,
    TableStyle,
    Paragraph,
    Spacer,
)


# Severity color mapping
SEVERITY_COLORS = {
    "CRITICAL": colors.HexColor("#FF3B4F"),
    "HIGH": colors.HexColor("#FF7B3B"),
    "MEDIUM": colors.HexColor("#FFB03B"),
    "LOW": colors.HexColor("#3BDD7C"),
}

SEVERITY_BG = {
    "CRITICAL": colors.HexColor("#2A0A10"),
    "HIGH": colors.HexColor("#2A1A0A"),
    "MEDIUM": colors.HexColor("#2A2A0A"),
    "LOW": colors.HexColor("#0A2A14"),
}


def _build_styles():
    """Create custom paragraph styles for the report."""
    styles = getSampleStyleSheet()

    styles.add(ParagraphStyle(
        "ReportTitle",
        parent=styles["Title"],
        fontSize=24,
        leading=30,
        textColor=colors.HexColor("#1A1A2E"),
        spaceAfter=4,
    ))
    styles.add(ParagraphStyle(
        "ReportSubtitle",
        parent=styles["Normal"],
        fontSize=11,
        textColor=colors.HexColor("#666680"),
        spaceAfter=20,
    ))
    styles.add(ParagraphStyle(
        "SectionHeader",
        parent=styles["Heading2"],
        fontSize=14,
        leading=18,
        textColor=colors.HexColor("#1A1A2E"),
        spaceBefore=16,
        spaceAfter=8,
        borderPadding=(0, 0, 4, 0),
    ))
    styles.add(ParagraphStyle(
        "BodyText2",
        parent=styles["Normal"],
        fontSize=10,
        leading=15,
        textColor=colors.HexColor("#333344"),
    ))
    styles.add(ParagraphStyle(
        "FooterStyle",
        parent=styles["Normal"],
        fontSize=9,
        textColor=colors.HexColor("#888899"),
        alignment=1,  # center
    ))
    return styles


def generate_pdf_report(impact_data: dict, ai_analysis: dict) -> bytes:
    """
    Generate a professional PDF impact analysis report.

    Args:
        impact_data: Dict with keys: object_name, risk_score, severity,
                     direct_impact (list of {name, type}),
                     indirect_impact (list of {name, type}),
                     all_impacted (list of names).
        ai_analysis: Dict with keys: root_cause, recommendations (list),
                     testing_checklist (list), rollback_plan (list).

    Returns:
        PDF file content as bytes.
    """
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        topMargin=0.6 * inch,
        bottomMargin=0.8 * inch,
        leftMargin=0.75 * inch,
        rightMargin=0.75 * inch,
    )
    styles = _build_styles()
    elements = []

    # ── Header ──────────────────────────────────────────────────────────
    elements.append(Paragraph("Impact Analysis Report", styles["ReportTitle"]))
    elements.append(Paragraph(
        "Oracle Pythia-26 &nbsp;|&nbsp; Generated by Impact Analysis Generator",
        styles["ReportSubtitle"],
    ))

    # Thin accent line
    line_table = Table([[""]],
                       colWidths=[doc.width],
                       rowHeights=[2])
    line_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#00D4FF")),
        ("LINEBELOW", (0, 0), (-1, -1), 0, colors.white),
    ]))
    elements.append(line_table)
    elements.append(Spacer(1, 16))

    # ── Target Object ───────────────────────────────────────────────────
    elements.append(Paragraph("Target Object", styles["SectionHeader"]))
    obj_name = impact_data.get("object_name", "N/A")
    obj_type = impact_data.get("object_type", "UNKNOWN")
    # Try to figure out object type from direct/indirect info or graph
    if obj_type == "UNKNOWN":
        obj_type = impact_data.get("type", "OBJECT")

    target_table = Table(
        [["Name", obj_name], ["Type", obj_type]],
        colWidths=[1.2 * inch, 4.5 * inch],
        rowHeights=[24, 24],
    )
    target_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#F0F0F8")),
        ("TEXTCOLOR", (0, 0), (0, -1), colors.HexColor("#666680")),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#DDDDEE")),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
    ]))
    elements.append(target_table)
    elements.append(Spacer(1, 12))

    # ── Risk Score ──────────────────────────────────────────────────────
    elements.append(Paragraph("Risk Score", styles["SectionHeader"]))
    severity = impact_data.get("severity", "LOW").upper()
    risk_score = impact_data.get("risk_score", 0)
    sev_color = SEVERITY_COLORS.get(severity, colors.gray)
    sev_bg = SEVERITY_BG.get(severity, colors.HexColor("#F0F0F0"))

    score_text = Paragraph(
        f'<font size="36" color="{sev_color.hexval()}">'
        f'<b>{risk_score}</b></font>'
        f'<font size="12" color="#888899"> / 100</font>',
        styles["BodyText2"],
    )
    badge_text = Paragraph(
        f'<font size="12" color="{sev_color.hexval()}">'
        f'<b>{severity}</b></font>',
        styles["BodyText2"],
    )
    score_table = Table(
        [[score_text, badge_text]],
        colWidths=[3 * inch, 2.5 * inch],
        rowHeights=[50],
    )
    score_table.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("BACKGROUND", (1, 0), (1, 0), sev_bg),
        ("ALIGN", (1, 0), (1, 0), "CENTER"),
        ("ROUNDEDCORNERS", [0, 8, 8, 0]),
    ]))
    elements.append(score_table)
    elements.append(Spacer(1, 12))

    # ── Impact Summary ──────────────────────────────────────────────────
    elements.append(Paragraph("Impact Summary", styles["SectionHeader"]))
    direct = impact_data.get("direct_impact", [])
    indirect = impact_data.get("indirect_impact", [])
    total = len(direct) + len(indirect)

    summary_data = [
        ["Direct Impacts", "Indirect Impacts", "Total Impacted"],
        [str(len(direct)), str(len(indirect)), str(total)],
    ]
    summary_table = Table(summary_data, colWidths=[1.9 * inch] * 3, rowHeights=[22, 36])
    summary_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1A1A2E")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 10),
        ("FONTSIZE", (0, 1), (-1, 1), 18),
        ("FONTNAME", (0, 1), (-1, 1), "Helvetica-Bold"),
        ("TEXTCOLOR", (0, 1), (0, 1), SEVERITY_COLORS.get("CRITICAL")),
        ("TEXTCOLOR", (1, 1), (1, 1), SEVERITY_COLORS.get("HIGH")),
        ("TEXTCOLOR", (2, 1), (2, 1), colors.HexColor("#1A1A2E")),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#DDDDEE")),
    ]))
    elements.append(summary_table)
    elements.append(Spacer(1, 12))

    # ── Direct Impacts Table ────────────────────────────────────────────
    if direct:
        elements.append(Paragraph("Direct Impacts", styles["SectionHeader"]))
        table_data = [["#", "Name", "Type"]]
        for i, obj in enumerate(direct, 1):
            table_data.append([str(i), obj.get("name", ""), obj.get("type", "")])
        t = Table(table_data, colWidths=[0.5 * inch, 3.5 * inch, 1.7 * inch])
        t.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1A1A2E")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F8F8FC")]),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#DDDDEE")),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("LEFTPADDING", (0, 0), (-1, -1), 6),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ]))
        elements.append(t)
        elements.append(Spacer(1, 10))

    # ── Indirect Impacts Table ──────────────────────────────────────────
    if indirect:
        elements.append(Paragraph("Indirect (Transitive) Impacts", styles["SectionHeader"]))
        table_data = [["#", "Name", "Type"]]
        for i, obj in enumerate(indirect, 1):
            table_data.append([str(i), obj.get("name", ""), obj.get("type", "")])
        t = Table(table_data, colWidths=[0.5 * inch, 3.5 * inch, 1.7 * inch])
        t.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1A1A2E")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F8F8FC")]),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#DDDDEE")),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("LEFTPADDING", (0, 0), (-1, -1), 6),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ]))
        elements.append(t)
        elements.append(Spacer(1, 10))

    # ── AI Analysis Sections ────────────────────────────────────────────
    # Root Cause
    root_cause = ai_analysis.get("root_cause", "")
    if root_cause:
        elements.append(Paragraph("AI Analysis — Root Cause", styles["SectionHeader"]))
        elements.append(Paragraph(root_cause, styles["BodyText2"]))
        elements.append(Spacer(1, 8))

    # Recommendations (numbered)
    recs = ai_analysis.get("recommendations", [])
    if recs:
        elements.append(Paragraph("AI Analysis — Recommendations", styles["SectionHeader"]))
        for i, rec in enumerate(recs, 1):
            elements.append(Paragraph(
                f"<b>{i}.</b> {rec}",
                styles["BodyText2"],
            ))
        elements.append(Spacer(1, 8))

    # Testing Checklist (bullets)
    checks = ai_analysis.get("testing_checklist", [])
    if checks:
        elements.append(Paragraph("AI Analysis — Testing Checklist", styles["SectionHeader"]))
        for item in checks:
            elements.append(Paragraph(
                f"&#8226; {item}",
                styles["BodyText2"],
            ))
        elements.append(Spacer(1, 8))

    # Rollback Plan (numbered)
    rollback = ai_analysis.get("rollback_plan", [])
    if rollback:
        elements.append(Paragraph("AI Analysis — Rollback Plan", styles["SectionHeader"]))
        for i, step in enumerate(rollback, 1):
            elements.append(Paragraph(
                f"<b>{i}.</b> {step}",
                styles["BodyText2"],
            ))
        elements.append(Spacer(1, 12))

    # ── Footer ──────────────────────────────────────────────────────────
    elements.append(Spacer(1, 20))
    footer_line = Table([[""]],
                        colWidths=[doc.width],
                        rowHeights=[1])
    footer_line.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#DDDDEE")),
    ]))
    elements.append(footer_line)
    elements.append(Spacer(1, 8))
    elements.append(Paragraph(
        "Team AI Elites (LTM) — Sameet, Rahul, Suraj, Arpan &nbsp;|&nbsp; Oracle Pythia-26 Hackathon",
        styles["FooterStyle"],
    ))

    # Build PDF
    doc.build(elements)
    return buf.getvalue()
